variables:
  model_name_or_path:

run_name: #TODO
save_folder: /home/eldar/llmfoundry_checkpoints_v2/llama3_8b_cosmopedia_alldownstream/${run_name}
save_weights_only: true

max_seq_len: #TODO
max_duration: #TODO
eval_interval: #TODO
global_train_batch_size: #TODO
device_train_microbatch_size: #TODO
device_eval_batch_size: #TODO
eval_first: true
precision: #TODO

seed: 42
dist_timeout: 5000
expandable_segments: true

save_interval: ${eval_interval}
save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
# save_folder: s3://my-bucket/my-folder/{run_name}/checkpoints

model:
  name: hf_causal_lm
  use_flash_attention_2: true
  pretrained: true
  pretrained_model_name_or_path: ${variables.model_name_or_path}
  use_auth_token: true

tokenizer:
  name: ${variables.model_name_or_path}
  kwargs:
    model_max_length: ${max_seq_len}

train_loader:
  name: text
  dataset:
    streams:
      shubhra_dedup:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/downstream_mix_shubhra_deduplicated
        local:
        split: train
      arc_8b:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/arcboth_datagen_wllama3_8b_instruct
        local:
        split: train
      winogrande_8b:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/winogrande_datagen_wllama3_8b_instruct
        local:
        split: train
      hellaswag_8b:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/hellaswag_datagen_wllama3_8b_instruct
        local:
        split: train
      mmlu_aux_8b:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/mmlu_datagen_wllama3_8b_instruct
        local:
        split: train
      openmathinstruct_1_8b:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/openmathinstruct1_datagen_wllama3_8b_instruct
        local:
        split: train
      arc_8b_young_children:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/arcboth_datagen_wllama3_8b_instruct_difficulty_young_children
        local:
        split: train
      winogrande_8b_young_children:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/winogrande_datagen_wllama3_8b_instruct_difficulty_young_children
        local:
        split: train
      hellaswag_8b_young_children:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/hellaswag_datagen_wllama3_8b_instruct_difficulty_young_children
        local:
        split: train
      mmlu_aux_8b_young_children:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/mmlu_datagen_wllama3_8b_instruct_difficulty_young_children
        local:
        split: train
      arc_8b_college_students:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/arcboth_datagen_wllama3_8b_instruct_difficulty_college_students
        local:
        split: train
      winogrande_8b_college_students:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/winogrande_datagen_wllama3_8b_instruct_difficulty_college_students
        local:
        split: train
      hellaswag_8b_college_students:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/hellaswag_datagen_wllama3_8b_instruct_difficulty_college_students
        local:
        split: train
      mmlu_aux_8b_college_students:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/mmlu_datagen_wllama3_8b_instruct_difficulty_college_students
        local:
        split: train
      arc_8b_scientists:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/arcboth_datagen_wllama3_8b_instruct_difficulty_scientists
        local:
        split: train
      winogrande_8b_scientists:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/winogrande_datagen_wllama3_8b_instruct_difficulty_scientists
        local:
        split: train
      hellaswag_8b_scientists:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/hellaswag_datagen_wllama3_8b_instruct_difficulty_scientists
        local:
        split: train
      mmlu_aux_8b_scientists:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b/seqlen8k_tokenized_wBOSandEOS_noDroppingSeqPack/mmlu_datagen_wllama3_8b_instruct_difficulty_scientists
        local:
        split: train
      finewebedu10bt:
        remote: /network/eldar/datasets/pretrain_with_position_ids/llama3_8b_FineWebEduSample10BT_seq8k_tokenized_wBOSandEOS_noDroppingSeqPack
        local:
        split: train
    max_seq_len: ${max_seq_len}
    shuffle: true
    shuffle_seed: ${seed}
    allow_pad_trimming: false
    decoder_only_format: true
  drop_last: true
  pin_memory: true
  num_workers: 8
  prefetch_factor: 2
  persistent_workers: true

scheduler:
  name: cosine_with_warmup
  t_warmup: #TODO
  alpha_f: 0.1

optimizer:
  name: decoupled_adamw
  lr: #TODO
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08
  weight_decay: 0.0

algorithms:
  mask_pruned_weights: {}
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 2.0

fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: true
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true

knowledge_distillation:
  teacher_name_or_path: #TODO
  temperature: #TODO
  hardness_kldiv: #TODO
  hardness_ce: #TODO
  hardness_squarehead: #TODO

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  lr_monitor: {}
  speed_monitor:
    window_size: 10
  memory_monitor: {}
  runtime_estimator: {}
  hf_checkpointer:
    overwrite: true
    precision: bfloat16
    save_folder: ${save_folder}
    save_interval: 1dur

loggers:
  wandb: {}
  clearml: {}

icl_seq_len: ${max_seq_len}
icl_tasks:
-
  label: arc_challenge
  dataset_uri: /home/eldar/eldar-upstream/upstream-llm-foundry/scripts/eval/local_data/world_knowledge/arc_challenge_shrinked.jsonl
  num_fewshot: [25]
  icl_task_type: multiple_choice
  continuation_delimiter: "\nAnswer: " # this separates questions from answers
  metric_names:
  - InContextLearningMultipleChoiceAccuracy
  - InContextLearningPerplexity
-
  label: mmlu
  dataset_uri: /home/eldar/eldar-upstream/upstream-llm-foundry/scripts/eval/local_data/world_knowledge/mmlu_shrinked.jsonl
  num_fewshot: [5]
  icl_task_type: multiple_choice
  continuation_delimiter: "\nAnswer: " # this separates questions from answers
  # has_categories: true  # this splits mmlu into separate categories; lets keep track of global average for now
  metric_names:
  - InContextLearningMultipleChoiceAccuracy
  - InContextLearningPerplexity
-
  label: hellaswag
  dataset_uri: /home/eldar/eldar-upstream/upstream-llm-foundry/scripts/eval/local_data/language_understanding/hellaswag_shrinked.jsonl
  num_fewshot: [10]
  icl_task_type: multiple_choice
  metric_names:
  - InContextLearningMultipleChoiceAccuracy
  - InContextLearningPerplexity
-
  label: winogrande
  dataset_uri: /home/eldar/eldar-upstream/upstream-llm-foundry/scripts/eval/local_data/language_understanding/winogrande_shrinked.jsonl
  num_fewshot: [5]
  icl_task_type: schema
  metric_names:
  - InContextLearningMultipleChoiceAccuracy
  - InContextLearningPerplexity
